### ISSUE TITLE
Java Exception occured

### ISSUE THREAD

**Issue by Mlebech** [dostaji4/EnergyPlus-co-simulation-toolbox#8]
Hi I am using Matlab R2021b and EnergyPlus 8.9.

During simulation, the communication between Simulink and Energy + failed and crashed. This error occured with a random frequency.
The logs are in attached file showing a problem of writing in the sockets in the bcvtb program. 

[log.zip](https://github.com/dostaji4/EnergyPlus-co-simulation-toolbox/files/8096888/log.zip)

**Comment by swancrow** [comment]
I have the same issue

**Comment by swancrow** [comment]
Error using mlep/acceptSocket (line 1146)
Java exception occurred:
java.net.SocketTimeoutException: Accept timed out

	at java.net.DualStackPlainSocketImpl.waitForNewConnection(Native Method)

	at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:135)

	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)

	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)

	at java.net.ServerSocket.implAccept(ServerSocket.java:545)

	at java.net.ServerSocket.accept(ServerSocket.java:513)

**Comment by ArafonaRoll** [comment]
I have encountered the same issue when using MATLAB 2023b and Energyplus 9.2. Has anyone found a solution to this?
